services:
  app:
    build: .
    image: inventedle:latest
    ports:
      - 127.0.0.1:3009:3000
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: always
  cron:
    image: iotd-cron:latest
    build:
      dockerfile: IOTD.Dockerfile
    restart: always
    env_file: .env
